version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: library
      MYSQL_USER: librarian
      MYSQL_PASSWORD: library123
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
volumes:
  db_data:
